### ISSUE TITLE
Can I log content elements other than downloads?

### ISSUE THREAD

**Issue by rocchidavide** [BugBuster1701/dlstats#90]
Hi,
sorry maybe this isn't the best place to ask but: I developed a Contao extension similar to download content element, but it get files from a Dropbox account (https://github.com/rocchidavide/contao-dropbox_tools). I saw your extension and could be very useful adapt it to work with mine; I've just installed your code and I'm trying to understand if is it possible.

**Comment by BugBuster1701** [comment]
"dlstats" used the hook "postDownload", to initiate the count.
Workflow: ce_download (ContentDownload.php) line 67,:
https://github.com/contao/core/blob/master/system/modules/core/elements/ContentDownload.php#L67
then in Controller.php line 1241, here is the call of the hook.
https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Controller.php#L1241

Your extension must only call the hook, the parameter is the file. Then dlstat count it.
So in this example you have to implement the lines 1241-1247
https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Controller.php#L1241-L1247

**Comment by rocchidavide** [comment]
First of all thank you so much for your quick response :)
I tried to add the call to the hook in my code, just before the redirect to the dropbox file, passing this url as parameter to the hook.. but it doesn't work. I'm afraid that the file must exist in the contao files/.. and this is a problem, because in my extension i have not files stored locally, but I redirect to dropbox external url...

**Comment by BugBuster1701** [comment]
"dlstats" ist activated? (System->Settings->Download statistics)
And, if you are logged in the backend, your download is not counted.

**Comment by rocchidavide** [comment]
Yeah, it works! I was trying logged in the backend... :D

**Comment by rocchidavide** [comment]
Yeah, it works!! I was trying logged in the backend... :D Thank you so much!
