### ISSUE TITLE
dlstats im BE nach System verschieben

### ISSUE THREAD

**Issue by 31er** [BugBuster1701/dlstats#93]
dlstats sollte von "Inhalte" nach "System" verschoben werden. Dort ist auch "Visitors" vorhanden (wenn man es installiert hat) und ich finde das dies auch die richtige Stelle dafür ist.

**Comment by BugBuster1701** [comment]
Realisierung in Contao 4 Bundle Version.
https://github.com/BugBuster1701/contao-dlstats-bundle/issues/9
